# Start from the official Ubuntu 22.04 base image
FROM ubuntu:22.04

# Prevent interactive dialogs from blocking builds
ENV DEBIAN_FRONTEND=noninteractive

# Update package lists, upgrade packages, and install some common tools
RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        vim \
        git \
        python3 \
        python3-pip \
        libgl1  \
        libsm6          \ 
      	libxext6        \ 
      	libxrender-dev  \
      	ffmpeg          \
    && rm -rf /var/lib/apt/lists/*
    
# Install OpenCV and other dependencies
RUN pip3 install --no-cache-dir opencv-contrib-python open3d numpy scipy matplotlib

# Set a working directory
WORKDIR /workspace/src

# If no specific command, you can leave the container at a shell
CMD ["python3", "main.py"]

